<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="Marketing.xsl" type="text/xsl"?>

<!DOCTYPE Marketing [
<!ELEMENT Marketing (Marketingdata)>
<!ELEMENT Marketingdata (DMY, Topsize, Topproducts, Numberpd, Amount)>
<!ELEMENT DMY (#PCDATA)>
<!ELEMENT Topsize (#PCDATA)>
<!ELEMENT Topproducts (#PCDATA)>
<!ELEMENT Numberpd (#PCDATA)>
<!ELEMENT Amount (#PCDATA)>
]>

<Marketing>
    <Marketingdata>
        <DMY>21/06/2023</DMY>
        <Topsize>L</Topsize>
        <Topproducts>Island Delight</Topproducts>
        <Numberpd>105PC</Numberpd>
        <Amount>51,590 Baht</Amount>
    </Marketingdata>

    <Marketingdata>
        <DMY>22/06/2023</DMY>
        <Topsize>M</Topsize>
        <Topproducts>Seafood Extreme</Topproducts>
        <Numberpd>209PC</Numberpd>
        <Amount>83,391 Baht</Amount>
    </Marketingdata>
    
    <Marketingdata>
        <DMY>23/06/2023</DMY>
        <Topsize>L</Topsize>
        <Topproducts>Spicy Chicken BBQ</Topproducts>
        <Numberpd>196PC</Numberpd>
        <Amount>68,404 Baht</Amount>
    </Marketingdata>

    <Marketingdata>
        <DMY>24/06/2023</DMY>
        <Topsize>M</Topsize>
        <Topproducts>Bacon Hokkaido Cheese</Topproducts>
        <Numberpd>318PC</Numberpd>
        <Amount>120,522 Baht</Amount>
    </Marketingdata>

    <Marketingdata>
        <DMY>25/06/2023</DMY>
        <Topsize>M</Topsize>
        <Topproducts>Pepperoni</Topproducts>
        <Numberpd>143PC</Numberpd>
        <Amount>42,757 Baht</Amount>
    </Marketingdata>
</Marketing>